import { useRef, useEffect } from 'react';
import { HiOutlineArrowRight, HiOutlineArrowLeft } from 'react-icons/hi';

const features = [
  {
    id: 1,
    title: "Edge AI Engineers",
    tag: "Development",
    metric: "Deploy & Optimize",
    image: "/images/fea_1.svg",
    desc: "Easily deploy and manage AI models across distributed edge infrastructure. Use our SDK to seamlessly integrate with frameworks like Jetson, JetPack, and DeepStream."
  },
  {
    id: 2,
    title: "Industrial Automation",
    tag: "Manufacturing",
    metric: "Real-Time Control",
    image: "/images/fea_2.svg",
    desc: "Reduce latency and bandwidth consumption by bringing operational intelligence directly to the factory floor without relying on centralized cloud processing."
  },
  {
    id: 3,
    title: "Smart City Operators",
    tag: "Infrastructure",
    metric: "Fleet Management",
    image: "/images/fea_3.svg",
    desc: "Manage thousands of distributed cameras and environmental sensors from a single, centralized Edge Operations Dashboard with unified health monitoring."
  },
  {
    id: 4,
    title: "Security Operations",
    tag: "Surveillance",
    metric: "Video Analytics",
    image: "/images/fea_4.svg",
    desc: "Process live video streams and execute object detection workflows locally for immediate autonomous threat response and operational awareness."
  },
  {
    id: 5,
    title: "Enterprise Technology",
    tag: "IT Operations",
    metric: "Hardware Monitor",
    image: "/images/fea_5.svg",
    desc: "Gain complete visibility into edge infrastructure performance, AI inference activity, device health, and network connectivity across global deployments."
  },
  {
    id: 6,
    title: "IoT Solution Providers",
    tag: "Integration",
    metric: "Sensor Telemetry",
    image: "/images/fea_6.svg",
    desc: "Collect, analyze, and act on massive volumes of data generated by connected sensor ecosystems with sub-second latency and absolute reliability."
  }
];

export default function EnterpriseScale() {
  const scrollRef = useRef(null);

  const scroll = (direction) => {
    const el = scrollRef.current;
    if (!el) return;
    const cardWidth = 350 + 24; // Card width + gap
    const scrollAmount = direction === 'left' ? -cardWidth : cardWidth;
    el.scrollBy({ left: scrollAmount, behavior: 'smooth' });
  };

  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;

    // Optional autoplay carousel logic
    let userScrolling = false;
    let resetTimer;
    const onInteract = () => {
      userScrolling = true;
      clearTimeout(resetTimer);
      resetTimer = setTimeout(() => { userScrolling = false; }, 3000);
    };
    el.addEventListener('touchstart', onInteract, { passive: true });
    el.addEventListener('mousedown', onInteract);

    const interval = setInterval(() => {
      if (userScrolling || !el) return;
      const { scrollLeft, scrollWidth, clientWidth } = el;
      const cardWidth = window.innerWidth >= 768 ? 350 + 24 : 320 + 24;
      if (scrollLeft + clientWidth >= scrollWidth - 10) {
        el.scrollTo({ left: 0, behavior: 'smooth' });
      } else {
        el.scrollBy({ left: cardWidth, behavior: 'smooth' });
      }
    }, 5000);

    return () => {
      clearInterval(interval);
      clearTimeout(resetTimer);
      el.removeEventListener('touchstart', onInteract);
      el.removeEventListener('mousedown', onInteract);
    };
  }, []);

  return (
    <section className="relative py-24 border-t border-white/5 overflow-hidden bg-transparent">
      
      {/* Background Isometric Grid */}
      <div className="absolute inset-0 z-0 opacity-20 pointer-events-none">
        <svg width="100%" height="100%">
          <defs>
            <pattern id="isometricGrid" width="40" height="23" patternUnits="userSpaceOnUse" patternTransform="scale(2)">
              <path d="M20,0 L40,11.5 L20,23 L0,11.5 Z" fill="none" stroke="rgba(212,20,255,0.2)" strokeWidth="0.5"/>
              <path d="M20,23 L20,46" fill="none" stroke="rgba(212,20,255,0.2)" strokeWidth="0.5"/>
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#isometricGrid)" />
        </svg>
      </div>

      <div className="max-w-[1400px] w-full mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Main Split Layout container */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-8 relative items-center">
          
          {/* Left Column (Sticky Text panel) */}
          <div className="lg:col-span-4 relative">
            <div className="lg:sticky lg:top-32 flex flex-col items-start pr-4 text-left">
              
              <div className="flex items-center gap-2 mb-4">
                <div className="w-2 h-2 rounded-full bg-primary shadow-[0_0_10px_rgba(212,20,255,0.8)]"></div>
                <span className="text-xs font-bold text-primary uppercase tracking-widest">Built For</span>
              </div>
              
              <h2 className="text-5xl md:text-6xl font-bold leading-tight mb-6 text-white drop-shadow-md">
                Enterprise<br/>Scale.
              </h2>
              
              <p className="text-lg text-textMuted font-medium leading-relaxed max-w-sm">
                Empowering teams to manage thousands of distributed cameras, sensors, and remote devices from a single centralized Operations Dashboard.
              </p>

              {/* Slider Controls (Matches chevron overlay in reference) */}
              <div className="flex gap-3 mt-6">
                <button 
                  onClick={() => scroll('left')}
                  className="w-11 h-11 rounded-full border border-white/10 hover:border-primary/50 flex items-center justify-center text-white/50 hover:text-white hover:bg-primary/20 transition-all cursor-pointer outline-none bg-[#0a0514]"
                  aria-label="Scroll left"
                >
                  <HiOutlineArrowLeft className="text-lg" />
                </button>
                <button 
                  onClick={() => scroll('right')}
                  className="w-11 h-11 rounded-full border border-white/10 hover:border-primary/50 flex items-center justify-center text-white/50 hover:text-white hover:bg-primary/20 transition-all cursor-pointer outline-none bg-[#0a0514]"
                  aria-label="Scroll right"
                >
                  <HiOutlineArrowRight className="text-lg" />
                </button>
              </div>

            </div>
          </div>

          {/* Right Column (Horizontal Carousel of structured vertical cards) */}
          <div className="lg:col-span-8 overflow-hidden rounded-2xl relative">
            
            {/* The Scrolling Container */}
            <div 
              ref={scrollRef}
              className="flex overflow-x-auto gap-6 pb-8 snap-x snap-mandatory hide-scrollbar relative z-10 pl-2 lg:pl-0 pt-2"
            >
              
              {features.map((feature, index) => (
                <div 
                  key={feature.id}
                  className="ent-card flex-none w-[320px] md:w-[350px] h-[560px] relative rounded-[32px] overflow-hidden snap-start group border border-white/10 shadow-[0_20px_40px_rgba(0,0,0,0.6)] cursor-pointer bg-[#0e091a]/90 p-6 flex flex-col justify-between hover:border-primary/20 transition-all duration-300"
                  style={{ animationDelay: `${index * 80}ms` }}
                >
                  
                  {/* Top content: Tag & Image */}
                  <div className="flex flex-col gap-4 text-left">
                    <span className="text-[10px] font-mono font-bold text-primary uppercase tracking-widest">
                      {feature.tag}
                    </span>

                    {/* SVG Image container */}
                    <div className="h-[250px] w-full bg-gradient-to-br from-[#1c1232]/50 to-[#0c0516]/50 rounded-2xl flex items-center justify-center border border-white/[0.03] overflow-hidden relative">
                      <img 
                        src={feature.image} 
                        alt={feature.title} 
                        className="w-full h-full object-cover object-center filter drop-shadow-[0_0_15px_rgba(212,20,255,0.15)] group-hover:scale-105 transition-transform duration-500 will-change-transform" 
                        loading="lazy"
                        decoding="async"
                      />
                    </div>
                  </div>

                  {/* Middle / Bottom text block */}
                  <div className="flex flex-col text-left gap-2 flex-grow justify-end mt-4">
                    <h3 className="text-xl font-bold text-white leading-tight group-hover:text-primary transition-colors">
                      {feature.title}
                    </h3>
                    
                    <p className="text-xs md:text-sm text-textMuted leading-relaxed font-light line-clamp-3">
                      {feature.desc}
                    </p>
                  </div>
                  
                  {/* Bottom Metric indicator row */}
                  <div className="mt-6 pt-4 border-t border-white/5 flex items-center justify-between">
                    <span className="text-xs font-bold text-white tracking-wide">
                      {feature.metric}
                    </span>
                  </div>
                  
                </div>
              ))}

            </div>
            
            {/* Scroll shadow indicator hint */}
            <div className="absolute right-0 top-0 bottom-8 w-24 bg-gradient-to-l from-background to-transparent pointer-events-none z-20 hidden lg:block"></div>
          </div>

        </div>
      </div>
      
      {/* CSS: hide scrollbar + lightweight card fade-in */}
      <style dangerouslySetInnerHTML={{__html: `
        .hide-scrollbar::-webkit-scrollbar { display: none; }
        .hide-scrollbar { -ms-overflow-style: none; scrollbar-width: none; }

        @keyframes entFadeUp {
          from { opacity: 0; transform: translateY(24px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .ent-card {
          opacity: 0;
          animation: entFadeUp 0.45s ease forwards;
        }
      `}} />
    </section>
  );
}
