import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { HiOutlineArrowRight, HiOutlineArrowLeft } from 'react-icons/hi';

const features = [
  {
    id: 1,
    title: "Edge AI Engineers",
    tag: "Development",
    metric: "Deploy & Optimize",
    image: "/images/fea_1.svg",
    desc: "Easily deploy and manage AI models across distributed edge infrastructure. Use our SDK to seamlessly integrate with frameworks like Jetson, JetPack, and DeepStream.",
    details: {
      metrics: [
        { label: "Latency", value: "12ms" },
        { label: "Compute", value: "Jetson" },
        { label: "Framework", value: "DeepStream" }
      ]
    }
  },
  {
    id: 2,
    title: "Industrial Automation",
    tag: "Manufacturing",
    metric: "Real-Time Control",
    image: "/images/fea_2.svg",
    desc: "Reduce latency and bandwidth consumption by bringing operational intelligence directly to the factory floor without relying on centralized cloud processing.",
    details: {
      metrics: [
        { label: "Latency", value: "4ms" },
        { label: "Compute", value: "PLC Link" },
        { label: "Encryption", value: "AES-256" }
      ]
    }
  },
  {
    id: 3,
    title: "Smart City Operators",
    tag: "Infrastructure",
    metric: "Fleet Management",
    image: "/images/fea_3.svg",
    desc: "Manage thousands of distributed cameras and environmental sensors from a single, centralized Edge Operations Dashboard with unified health monitoring.",
    details: {
      metrics: [
        { label: "Latency", value: "18ms" },
        { label: "Network", value: "5G Gateway" },
        { label: "Streams", value: "1000+ Cams" }
      ]
    }
  },
  {
    id: 4,
    title: "Security Operations",
    tag: "Surveillance",
    metric: "Video Analytics",
    image: "/images/fea_4.svg",
    desc: "Process live video streams and execute object detection workflows locally for immediate autonomous threat response and operational awareness.",
    details: {
      metrics: [
        { label: "Latency", value: "8ms" },
        { label: "Engine", value: "RT YOLOv8" },
        { label: "Response", value: "Autonomous" }
      ]
    }
  },
  {
    id: 5,
    title: "Enterprise Technology",
    tag: "IT Operations",
    metric: "Hardware Monitor",
    image: "/images/fea_5.svg",
    desc: "Gain complete visibility into edge infrastructure performance, AI inference activity, device health, and network connectivity across global deployments.",
    details: {
      metrics: [
        { label: "Latency", value: "10ms" },
        { label: "Protocol", value: "gRPC Streams" },
        { label: "Uptime", value: "99.99%" }
      ]
    }
  },
  {
    id: 6,
    title: "IoT Solution Providers",
    tag: "Integration",
    metric: "Sensor Telemetry",
    image: "/images/fea_6.svg",
    desc: "Collect, analyze, and act on massive volumes of data generated by connected sensor ecosystems with sub-second latency and absolute reliability.",
    details: {
      metrics: [
        { label: "Latency", value: "2ms" },
        { label: "Protocol", value: "MQTT/TLS" },
        { label: "Reliability", value: "Absolute" }
      ]
    }
  }
];

export default function EnterpriseScale() {
  const [activeIndex, setActiveIndex] = useState(0);
  const [progress, setProgress] = useState(0);
  const activeFeature = features[activeIndex];
  const timerRef = useRef(null);

  // Auto rotation logic (changes slide every 6 seconds)
  useEffect(() => {
    setProgress(0);
    const intervalTime = 6000;
    const updateRate = 100;
    let elapsed = 0;

    if (timerRef.current) clearInterval(timerRef.current);

    timerRef.current = setInterval(() => {
      elapsed += updateRate;
      setProgress((elapsed / intervalTime) * 100);

      if (elapsed >= intervalTime) {
        setActiveIndex((prev) => (prev + 1) % features.length);
        elapsed = 0;
      }
    }, updateRate);

    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [activeIndex]);

  const handleNext = () => {
    setActiveIndex((prev) => (prev + 1) % features.length);
  };

  const handlePrev = () => {
    setActiveIndex((prev) => (prev - 1 + features.length) % features.length);
  };

  return (
    <section className="relative py-24 border-t border-white/5 overflow-hidden bg-transparent">
      
      {/* Background Isometric Grid */}
      <div className="absolute inset-0 z-0 opacity-20 pointer-events-none">
        <svg width="100%" height="100%">
          <defs>
            <pattern id="isometricGrid" width="40" height="23" patternUnits="userSpaceOnUse" patternTransform="scale(2)">
              <path d="M20,0 L40,11.5 L20,23 L0,11.5 Z" fill="none" stroke="rgba(212,20,255,0.2)" strokeWidth="0.5"/>
              <path d="M20,23 L20,46" fill="none" stroke="rgba(212,20,255,0.2)" strokeWidth="0.5"/>
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#isometricGrid)" />
        </svg>
      </div>

      <div className="max-w-[1400px] w-full mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Section Header */}
        <div className="text-left mb-16 max-w-3xl">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-2 h-2 rounded-full bg-primary shadow-[0_0_10px_rgba(212,20,255,0.8)]"></div>
            <span className="text-xs font-bold text-primary uppercase tracking-widest">Built For</span>
          </div>
          
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-6 drop-shadow-md leading-tight">
            Enterprise Scale.
          </h2>
          
          <p className="text-base md:text-lg text-textMuted font-medium leading-relaxed">
            Empowering teams to manage thousands of distributed cameras, sensors, and remote devices from a single centralized Operations Dashboard.
          </p>
        </div>

        {/* Dynamic Split Screen Interactive Console */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center bg-[#0e091a]/80 border border-white/10 rounded-[32px] p-8 md:p-12 shadow-[0_30px_60px_rgba(0,0,0,0.85)] relative min-h-[560px]">
          
          {/* Left Column: Massive SVG Illustration Viewport (No outer border, maximum scale) */}
          <div className="lg:col-span-6 flex items-center justify-center relative h-[380px] md:h-[480px] w-full">
            
            <AnimatePresence mode="wait">
              <motion.div
                key={activeIndex}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ duration: 0.4 }}
                className="w-full h-full flex items-center justify-center"
              >
                <img 
                  src={activeFeature.image} 
                  alt={activeFeature.title} 
                  className="w-full h-full object-contain filter drop-shadow-[0_0_30px_rgba(212,20,255,0.25)]"
                  loading="lazy"
                  decoding="async"
                />
              </motion.div>
            </AnimatePresence>
          </div>

          {/* Right Column: Dynamic Feature Details Card */}
          <div className="lg:col-span-6 flex flex-col justify-between h-full text-left">
            <AnimatePresence mode="wait">
              <motion.div
                key={activeIndex}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.35, ease: "easeOut" }}
                className="flex flex-col gap-6"
              >
                {/* Header Tag / Console Title */}
                <div className="flex items-center gap-3">
                  <span className="text-[10px] font-mono font-bold text-primary uppercase tracking-widest bg-primary/10 border border-primary/20 px-3 py-1 rounded">
                    {activeFeature.tag}
                  </span>
                  <span className="text-xs text-white/40 font-mono">
                    CONSOLE HOST // NODE_0{activeFeature.id}
                  </span>
                </div>

                {/* Main Title */}
                <h3 className="text-3xl md:text-4xl font-bold text-white tracking-tight leading-tight">
                  {activeFeature.title}
                </h3>

                {/* Main Description */}
                <p className="text-sm md:text-base text-textMuted leading-relaxed font-light max-w-xl">
                  {activeFeature.desc}
                </p>

                {/* 3-Column Diagnostic Metrics Grid */}
                <div className="grid grid-cols-3 gap-2 text-center bg-white/[0.01] border border-white/5 rounded-2xl p-4 divide-x divide-white/5">
                  {activeFeature.details.metrics.map((metric, idx) => (
                    <div key={idx} className="flex flex-col justify-center px-1">
                      <span className="text-[9px] text-white/40 uppercase tracking-wider font-semibold">
                        {metric.label}
                      </span>
                      <span className="text-sm md:text-base font-bold text-white mt-1 font-mono">
                        {metric.value}
                      </span>
                    </div>
                  ))}
                </div>

                {/* Slider Control Action HUD */}
                <div className="flex items-center justify-between mt-4 pt-6 border-t border-white/5">
                  
                  {/* Metric Display */}
                  <span className="text-xs font-bold text-white tracking-wider">
                    Target: {activeFeature.metric}
                  </span>

                  {/* Nav Controls */}
                  <div className="flex gap-3">
                    <button 
                      onClick={handlePrev}
                      className="w-10 h-10 rounded-xl bg-white/5 border border-white/10 hover:border-primary/50 text-white flex items-center justify-center hover:bg-primary/20 transition-all cursor-pointer outline-none"
                    >
                      <HiOutlineArrowLeft />
                    </button>
                    <button 
                      onClick={handleNext}
                      className="w-10 h-10 rounded-xl bg-white/5 border border-white/10 hover:border-primary/50 text-white flex items-center justify-center hover:bg-primary/20 transition-all cursor-pointer outline-none"
                    >
                      <HiOutlineArrowRight />
                    </button>
                  </div>
                </div>

              </motion.div>
            </AnimatePresence>
          </div>

        </div>

        {/* 6-Column Bottom Console Tabs (with automatic progress loaders) */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mt-8 relative z-10">
          {features.map((feature, index) => {
            const isActive = activeIndex === index;
            return (
              <button
                key={feature.id}
                onClick={() => setActiveIndex(index)}
                className={`text-left p-4 rounded-xl border transition-all duration-300 flex flex-col justify-between h-[85px] outline-none cursor-pointer relative overflow-hidden ${
                  isActive 
                    ? 'bg-[#160f29]/50 border-primary/40 shadow-md' 
                    : 'bg-black/20 border-white/5 hover:border-white/10 hover:bg-black/30'
                }`}
              >
                {/* Node tag / index */}
                <div className="flex items-center justify-between w-full">
                  <span className={`text-[9px] font-mono font-bold ${isActive ? 'text-primary' : 'text-white/30'}`}>
                    0{feature.id}
                  </span>
                  <span className="text-[8px] text-white/30 uppercase tracking-widest font-semibold hidden md:inline">
                    {feature.tag}
                  </span>
                </div>

                {/* Title */}
                <span className={`text-xs font-bold transition-colors leading-tight line-clamp-1 ${
                  isActive ? 'text-white' : 'text-white/60'
                }`}>
                  {feature.title}
                </span>

                {/* Progress bar at the bottom */}
                <div className="absolute bottom-0 left-0 right-0 h-[2px] bg-white/[0.04]">
                  {isActive && (
                    <motion.div 
                      className="h-full bg-primary"
                      style={{ width: `${progress}%` }}
                    />
                  )}
                </div>
              </button>
            );
          })}
        </div>

      </div>
    </section>
  );
}
